### ISSUE TITLE
Several `console.log()` invocations aren't behind the debug boolean.

### ISSUE THREAD

**Issue by rhlowe** [antoniobrandao/ab-slideshow#1]
On several lines, `console.log()` does its thing and it is polluting the console with unneeded information. These logs should be dependent on `this.settings.debug`.

**Comment by antoniobrandao** [comment]
Hey @rhlowe thanks for your attention, and contribution which is very welcome. This case is a good reminder to keep my code more clean :) I'm taking in your pull request, thanks very much for sending it!

**Comment by rhlowe** [comment]
Happy to help @antoniobrandao!
